version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: study_planner_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - study_planner_net
    restart: always

  backend:
    build: ./backend
    container_name: study_planner_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/studyplanner
      - CLIENT_URL=http://localhost:80
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongodb
    networks:
      - study_planner_net
    restart: always

  worker:
    build: ./backend
    container_name: study_planner_worker
    command: ["node", "worker.js"]
    environment:
      - MONGO_URI=mongodb://mongodb:27017/studyplanner
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongodb
    networks:
      - study_planner_net
    restart: always

  frontend:
    build: ./frontend
    container_name: study_planner_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - study_planner_net
    restart: always

volumes:
  mongo_data:

networks:
  study_planner_net:
    driver: bridge
